"""empty message

Revision ID: 36eb4baa718
Revises: None
Create Date: 2015-07-27 16:24:55.743424

"""

# revision identifiers, used by Alembic.
revision = '36eb4baa718'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photographer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('photo',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('photographer_id', sa.Integer(), nullable=True),
    sa.Column('taken_at', sa.DateTime(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('size', sa.String(length=120), nullable=True),
    sa.Column('exif', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['photographer_id'], ['photographer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photo')
    op.drop_table('photographer')
    ### end Alembic commands ###
